version: "3.8"

services:
  licensing-service:
    build:
      context: ./licensing-service
      dockerfile: Dockerfile
    ports:
       - "8080:8080"
    networks:
      backend:
        aliases:
          - "licenseservice"

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
  license-db:
    image: postgres:17.5
    restart: "no"
    ports:
      - "5434:5432"
    volumes:
      - license-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostock_dev

volumes:
  license-db:

networks:
  backend:
    driver: bridge