server:
  port: 8081

spring:
  application:
    name: organization-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://configserver:8071
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        max-attempts: 100
  jpa:
    hibernate:
      ddl-auto: update