server:
  port: 8761

spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://configserver:8071
    cloud:
      config:
        uri: http://configserver:8071
        fail-fast: true
        retry:
          initial-interval: 3000
          max-interval: 10000
          max-attempts: 10
        import-check:
            enabled: false