eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
    healthcheck:
      enabled: true
      initial-instance-info-replication-interval-seconds: 5
      registry-fetch-interval-seconds: 5


spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/licensing/**
          filters:
             - RewritePath=/licensing/(?<path>.*), /$\{path}
             - TokenRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/spmia-realm"
          jwk-set-uri: "http://keycloak:8080/realms/spmia-realm/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG