example:
  property: I AM DEV

spring:
  datasource:
    url: jdbc:postgresql://license-db:5432/ostock_dev
    username: "{cipher}4fe9091c741a1c9a387904e2d09b5216b486394d5f6033218e297738d9505639"
    password: "{cipher}4fe9091c741a1c9a387904e2d09b5216b486394d5f6033218e297738d9505639"
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/spmia-realm"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/

logging:
  level:
    io.github.resilience4j: DEBUG

resilience4j.circuitbreaker:
  instances:
    licenseService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 5
      waitDurationInOpenState: 10s
      failureRateThreshold: 70
      recordException:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
    organizationService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60

resilience4j.bulkhead:
  instances:
    bulkheadLicenseService:
      maxThreadPoolSize: 20
      coreThreadPoolSize: 10
      queueCapacity: 50
      keepAliveDuration: 500ms

resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadLicenseService:
      maxThreadPoolSize: 10
      coreThreadPoolSize: 5
      queueCapacity: 100
      keepAliveDuration: 100ms

resilience4j.retry:
  instances:
    retryLicenseService:
      maxRetryAttempts: 3
      waitDuration: 500
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  instances:
    licenseService:
      timeoutDuration: 1000ms
      limitRefreshPeriod: 1s
      limitForPeriod: 20